version: "3"
services:
  natechoe.dev:
    image: natechoe/natechoe.dev
    container_name: natechoe.dev
    ports:
      - "198.251.83.152:443:443"
      - "198.251.83.152:200:80"
        # Port 200 is used for the tor hidden service. I'd rather not use port
        # 80 because the .dev domain has HSTS and Let's Encrypt has to have port
        # 80 open
    volumes:
      - /etc/letsencrypt/live/natechoe.dev/privkey.pem:/secrets/privkey.pem:ro
      - /etc/letsencrypt/live/natechoe.dev/fullchain.pem:/secrets/fullchain.pem:ro
      - ./tor-data:/tor-data
    working_dir: "/site/"
    restart:
      always
    networks:
      natechoedev_network:
        ipv4_address: 10.1.123.2
  natechoe.dev-onion:
    image: natechoe/tor-relay
    container_name: natechoe.dev-onion
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tor-data:/var/lib/tor/tor-data
      - ./torrc:/etc/tor/torrc
    environment:
      - RELAY_EXPERT=1
    restart:
      always
    networks:
      natechoedev_network:

networks:
  natechoedev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.123.0/24
