version: "3"
services:
  natechoe.dev:
    image: natechoe/natechoe.dev
    container_name: natechoe.dev
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - ./tor-data:/tor-data
      - ./site:/site
    working_dir: "/site/"
    restart: always
    stop_grace_period: 0s
