version: "3"
services:
  natechoe.dev:
    image: natechoe/natechoe.dev
    container_name: natechoe.dev
    ports:
      - "127.0.0.1:8000:80"
    volumes:
      - ./tor-data:/tor-data
    working_dir: "/site/"
    restart: on-failure
    stop_grace_period: 2s
